### ISSUE TITLE
cannot use xreg in hts forecast

### ISSUE THREAD

**Issue by xiesong** [config-i1/smooth#106]
thank you for a very nice package. I can finally use exogenous variables in exponential smoothing. However when I use xreg in hts package for hierarchical forecasting, I'm unable to use newxreg and also xreg is not working properly. Can you please let me know if es can be used in hts with xreg and newxreg ?

> library("hts")
> y <- hts(m_ts, characters = c(5,2,2))
> xreg.c <- as.matrix(read.csv("xreg.csv"))
> htsforecast <- forecast(y, FUN=es,h=11,xreg=xreg.c)

**Comment by config-i1** [comment]
Hi xiesong,

Unfortunately, smooth functions are not available in hts package. You would need to create an issue in the respective repository: https://github.com/earowang/hts/issues/ - and ask them to make use of smooth functions.
The other option would be to somehow create a wrapper function that would allow using es() together with hts.
Overall, this cannot be fixed in the smooth package.

Cheers,
Ivan
