### ISSUE TITLE
How to pass two exogenous variables to xreg

### ISSUE THREAD

**Issue by andreykirson** [config-i1/smooth#116]
I've tried to pass two variables to xreg, but I've get error:

Warning: Error in ssXreg: (list) object cannot be coerced to type 'double'

The part of code where I pass the exogenous variables to xreg:

```
Promo <- data.frame(as.numeric(total_for_forecast$Promo));
Mean_Price <- data.frame(as.numeric(total_for_forecast$Mean_Price));
ts_model <- ts(ts_buffer, frequency = 7, start = 1);
forecast_model <- es(ts_model, "ZZM", h=h_forecast, xreg = c(Promo, Mean_Price), intervals = "np");
```

**Comment by config-i1** [comment]
Unfortunately, I cannot reproduce this error, because I don't have `total_for_forecast` and `ts_buffer` objects. So, I'm afraid I cannot help. But I noticed that the xreg is passed incorrectly: it should be `xreg = cbind(Promo, Mean_Price)` instead of `xreg = c(Promo, Mean_Price)`. Can it be that this is the reason for the error?

**Comment by config-i1** [comment]
One more thing, I would recommend doing this instead of what you do with xreg:
`Promo <- as.vector(total_for_forecast$Promo)`
Because you need to pass either a matrix or a data.frame to xreg in the end. And doing what you do might cause some problems with the object you provide. Thus this is not an error of es(), but a problem with your xreg.

**Comment by andreykirson** [comment]
cbind(Promo, Mean_Price) fix it. 

Thanks a lot!
