### ISSUE TITLE
Multiple Errors on an M3 series

### ISSUE THREAD

**Issue by AnscombesGimlet** [config-i1/smooth#143]
Hello - here is an error I came across when trying to use the es function on M3 data. Love the package by the way, auto.gum and smoothCombine are amazing.

```
library(Mcomp)

library(smooth)

es(M3[[912]]$x, model = "CCC", h=8)
```

Warning messages:

1: Negative values produced in the level of state vector of model MAN.
We had to substitute them by low values. Please, use a different model. 
2: In log(1 + errors * ot) : NaNs produced
3: Negative values produced in the level of state vector of model MAM.
We had to substitute them by low values. Please, use a different model. 
4: In log(1 + errors * ot) : NaNs produced
5: In log(1 + vecg %*% as.vector(errors * ot)) : NaNs produced
6: In log(1 + vecg %*% as.vector(errors * ot)) : NaNs produced

**Comment by config-i1** [comment]
Thanks for reporting this!
This is now fixed in 18f15d5b4c0370856504b6349aabb4230753f61d Please, let me know if the error appears again. There is an issue in the optimisation of mixed models - the function sometimes struggles to find adequate values.

Also, please, keep in mind that both auto.gum and smoothCombine are experimental functions. The former does not even have a supporting paper, while the latter performed quite poorly in M4 competition. They both still need to be improved.
